DECLARE @INI AS SMALLDATETIME, @FIM AS SMALLDATETIME
SET @INI = '20211101'
SET @FIM = '20211201'

--drop table 
--[ ELABORA UMA BASE DE CHAMADAS TEMPORÁRIA ]
IF(OBJECT_ID('TEMPDB.DBO.#CHAMADAS') IS NOT NULL) BEGIN DROP TABLE #CHAMADAS END
SELECT	R.REF_DATA
		, R.BILHETE
		, R.TELEFONE
		, R.DATA_INI
		, R.NIVEL_ATENDIMENTO
INTO #CHAMADAS
FROM
					(
					SELECT	DISTINCT E.BILHETE 
							,E.REF_DATA
							, E.TELEFONE
							, E.DATA_INI
							, NIVEL_ATENDIMENTO = ISNULL(C.NIVEL_ATENDIMENTO,0)
					FROM [SNEPDB39C01].[ATH].[FAT].[TB_F_ECH_CORP_VAR] E --WITH(INDEX(IDX_REF_DATA))		-- Faturamento do Variavel
						LEFT JOIN [FATURAMENTO].[TB_D_SITE] ST 
							ON E.ID_TB_D_SITE = ST.ID_TB_D_SITE 
								AND E.REF_DATA BETWEEN ST.DATA_INI AND ST.DATA_FIM
						LEFT JOIN [FATURAMENTO].[TB_D_SITE_VDN] C 
							ON ST.ID_SITE = C.ID_SITE 
								AND E.VDN = C.VDN 
								AND E.REF_DATA BETWEEN C.DATA_INI AND C.DATA_FIM
					WHERE	E.REF_DATA BETWEEN @INI AND @FIM
						--AND PRIMEIRO_CONTATO_BILHETE = 1	-- pega a primeira linha do bilhete

					UNION ALL

					SELECT	DISTINCT E.BILHETE
							, E.REF_DATA
							, E.TELEFONE
							, E.DATA_INI
							, NIVEL_ATENDIMENTO = ISNULL(C.NIVEL_ATENDIMENTO,0)
					FROM [SNEPDB39C01].[ATH].[FAT].TB_F_ECH_FIX E ---WITH(INDEX(IDX_REF_DATA))		-- Faturamento do Fixo
						LEFT JOIN [FATURAMENTO].[TB_D_SITE] ST 
							ON E.ID_TB_D_SITE = ST.ID_TB_D_SITE 
								AND E.REF_DATA BETWEEN ST.DATA_INI AND ST.DATA_FIM
						LEFT JOIN [FATURAMENTO].[TB_D_SITE_VDN] C 
							ON ST.ID_SITE = C.ID_SITE 
								AND E.VDN = C.VDN 
								AND E.REF_DATA BETWEEN C.DATA_INI AND C.DATA_FIM
					WHERE	E.REF_DATA BETWEEN @INI AND @FIM
						--AND PRIMEIRO_CONTATO_BILHETE = 1	-- pega a primeira linha do bilhete
					)R

SELECT * FROM #CHAMADAS