DECLARE @INI AS SMALLDATETIME, @FIM AS SMALLDATETIME
SET @INI = '20211101'
SET @FIM = '20211201'

--drop table 
--[ ELABORA UMA BASE DE CHAMADAS TEMPORÁRIA ]
IF(OBJECT_ID('TEMPDB.DBO.#CHAMADAS') IS NOT NULL) BEGIN DROP TABLE #CHAMADAS END
SELECT	R.REF_DATA
		, R.BILHETE
		, R.TELEFONE
		, R.DATA_INI
		, R.NIVEL_ATENDIMENTO
INTO #CHAMADAS
FROM
					(
					SELECT	DISTINCT E.BILHETE 
							,E.REF_DATA
							, E.TELEFONE
							, E.DATA_INI
							, NIVEL_ATENDIMENTO = ISNULL(C.NIVEL_ATENDIMENTO,0)
					FROM [SNEPDB39C01].[ATH].[FAT].[TB_F_ECH_CORP_VAR] E --WITH(INDEX(IDX_REF_DATA))		-- Faturamento do Variavel
						LEFT JOIN [FATURAMENTO].[TB_D_SITE] ST 
							ON E.ID_TB_D_SITE = ST.ID_TB_D_SITE 
								AND E.REF_DATA BETWEEN ST.DATA_INI AND ST.DATA_FIM
						LEFT JOIN [FATURAMENTO].[TB_D_SITE_VDN] C 
							ON ST.ID_SITE = C.ID_SITE 
								AND E.VDN = C.VDN 
								AND E.REF_DATA BETWEEN C.DATA_INI AND C.DATA_FIM
					WHERE	E.REF_DATA BETWEEN @INI AND @FIM
						--AND PRIMEIRO_CONTATO_BILHETE = 1	-- pega a primeira linha do bilhete

					UNION ALL

					SELECT	DISTINCT E.BILHETE
							, E.REF_DATA
							, E.TELEFONE
							, E.DATA_INI
							, NIVEL_ATENDIMENTO = ISNULL(C.NIVEL_ATENDIMENTO,0)
					FROM [SNEPDB39C01].[ATH].[FAT].TB_F_ECH_FIX E ---WITH(INDEX(IDX_REF_DATA))		-- Faturamento do Fixo
						LEFT JOIN [FATURAMENTO].[TB_D_SITE] ST 
							ON E.ID_TB_D_SITE = ST.ID_TB_D_SITE 
								AND E.REF_DATA BETWEEN ST.DATA_INI AND ST.DATA_FIM
						LEFT JOIN [FATURAMENTO].[TB_D_SITE_VDN] C 
							ON ST.ID_SITE = C.ID_SITE 
								AND E.VDN = C.VDN 
								AND E.REF_DATA BETWEEN C.DATA_INI AND C.DATA_FIM
					WHERE	E.REF_DATA BETWEEN @INI AND @FIM
						--AND PRIMEIRO_CONTATO_BILHETE = 1	-- pega a primeira linha do bilhete
					)R

	---select * from #CHAMADAS where REF_DATA = '20210921'
--	drop table #BASE_UNICA
	--[ CRIA UMA BASE UNICA TEMPORARIA PARA UNIR OS MAILINGS DE MARCO/ABRIL/MAIO ]---
	IF(OBJECT_ID('TEMPDB.DBO.#BASE_UNICA') IS NOT NULL) BEGIN DROP TABLE #BASE_UNICA END
	SELECT	TELEFONE
			, PLANO
			, DATA_ATIVACAO
		INTO #BASE_UNICA
	FROM [LS_PORTALCRCDB].[DM_ESTUDO].[DBO].[STG_MAILING_WELCOME_V2]	

		--[ ACRESCENTA A PARCIAL DE JUNHO ]---
--INSERT INTO #BASE_UNICA
--SELECT	TELEFONE,  PLANO, DATA_ATIVACAO
--FROM [LS_PORTALCRCDB].[DM_ESTUDO].[DBO].[STG_MAILING_WELCOME_FINAL] 
--WHERE DATA_ATIVACAO >= '20210601'


	--analise
	--	select top 10 * FROM [SNEPDB39C01].[ATH].[FAT].TB_F_ECH_FIX
	
	--[ CRIA UM LISTA FINAL, RETIRANDO A DUPLICIDADE ATRAVES DA MENOR DATA DE ATIVAÇÃO OLHANDO TELEFONE E PLANO ]---
	IF(OBJECT_ID('TEMPDB.DBO.#LISTA_INICIAL') IS NOT NULL) BEGIN DROP TABLE #LISTA_INICIAL END
    SELECT  DISTINCT TELEFONE
	       -- ,BILHETE
			, PLANO
			, DATA_INI = (DATA_ATIVACAO)
			, DATA_FIM = DATEADD(D,70,MIN(DATA_ATIVACAO))		-- O objetivo é olhar 70 dias após a ativação
		into #LISTA_INICIAL
	FROM #BASE_UNICA	          
	GROUP BY TELEFONE, PLANO, DATA_ATIVACAO

	SELECT	C.REF_DATA, C.TELEFONE, C.BILHETE, C.DATA_INI, C.NIVEL_ATENDIMENTO
	FROM	#LISTA_INICIAL L INNER JOIN #CHAMADAS C ON L.TELEFONE = C.TELEFONE AND C.REF_DATA BETWEEN L.DATA_INI AND L.DATA_FIM
	--where C.REF_DATA = '20210921' and telefone = '41998293659'
	
	---select * from #chamadas where data = '51982511091'
	--select *
	--FROM [SNEPDB39C01].[ATH].[FAT].[TB_F_ECH_VAR] where 
	--REF_DATA = '20210717' 
	--and 
	---telefone = '51982511091'
	----bilhete = '15359969597'